# Generated by Django 3.2.7 on 2021-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_rename_documents_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
