# Generated by Django 3.2.7 on 2021-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0003_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='photo',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
