# Generated by Django 3.2.7 on 2021-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0005_alter_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filetype',
            field=models.CharField(choices=[('graphic', 'GRAPHIC'), ('code', 'CODE')], default='graphic', max_length=16),
        ),
    ]
