# Generated by Django 3.2.7 on 2021-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0006_document_filetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='document',
            name='filetype',
            field=models.CharField(choices=[('graphic', 'GRAPHIC'), ('code', 'CODE'), ('hr', 'HR'), ('document', 'DOCUMENT'), ('other', 'OTHER')], default='graphic', max_length=16),
        ),
    ]
